apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: management-port
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: messaging-port
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: microshop

