version: '3.4'

services:
    seq:
        #container_name: seq
        image: datalust/seq
        ports: 
            - 5341:80
        environment:
          - ACCEPT_EULA=Y
    sql:
        #container_name: customer-db
        build:
            context: .
            dockerfile: sql/sql.Dockerfile
        restart: always
        ports:
            - 1433:1433   
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=M!cr@sh@p