version: '3.4'

services:
    api:
        container_name: customer-api-dc
        image: thegeekspad/microshop-customer-microservice
        depends_on:
            - seq
            - sql
            - rabbitmq
        env_file:
            - .env
        ports:
            - 5000:80
        networks:
            - customer-api-network
    seq:
        container_name: seq-dc
        image: datalust/seq
        ports: 
            - 5341:80
        env_file:
            - .env
        networks:
            - customer-api-network
    sql:
        container_name: customer-db-dc
        build:
            context: .
            dockerfile: sql/prod/sql.Dockerfile
        restart: always
        ports:
            - 1440:1433   
        env_file:
            - .env
        networks:
            - customer-api-network
    rabbitmq:  
        container_name: rabbitmq-dc
        image: rabbitmq:3.8  
        ports:
            - 5672:5672   
        networks:
            - customer-api-network
networks:
  customer-api-network:



