apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app-service: customer
spec:
  selector:
    matchLabels:
      app-service: customer
  replicas: 1
  template:
    metadata:
      labels:
        app-service: customer
    spec:
      containers:
        - name: customer-deployment-container
          image: thegeekspad/microshop-customer-microservice
          ports:
          - name: http-port
            containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: customer-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector: # this connects the service to the pods
    app-service: customer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-node-port-service
spec:
  type: NodePort
  ports:
    - port: 80 # this is the port on the service object and mapped to the node port
      targetPort: 80 # this is the port on the pod
      nodePort: 30001 # this is the port exposed on the node. Valid range is 30000-32767.
  selector: # this connects the service to the pods
    app-service: customer

