apiVersion: v1
kind: Service
metadata:
  name: customer-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector: # this connects the service to the pods
    app-service: customer
