apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app-service: customer
spec:
  selector:
    matchLabels:
      app-service: customer
  replicas: 2
  template:
    metadata:
      labels:
        app-service: customer
    spec:
      containers:
        - name: customer-deployment-container
          image: thegeekspad/microshop-customer-microservice
          ports:
          - name: http-port
            containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/home
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/home
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 1
