apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api-deployment
  labels:
    app-service: customer
spec:
  selector:
    matchLabels:
      app-service: customer
  replicas: 2
  template:
    metadata:
      labels:
        app-service: customer
    spec:
      containers:
        - name: customer-deployment-container
          image: thegeekspad/microshop-customer-microservice
          ports:
              - name: http-port
                containerPort: 80
          env:
              - name: ACCEPT_EULA
                value: "Y"
              - name: SA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: customer-api-secret
                    key: SA_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 1
