apiVersion: v1
kind: Pod
metadata:
  name: customer-pod
  labels:
    app-service: customer
spec:
  containers:
  - name: customer-pod-container
    image: thegeekspad/microshop-customer-microservice
    ports:
    - name: http-port
      containerPort: 80
    - name: https-port
      containerPort: 443
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"