apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: customer-db
  template:
    metadata:
      labels:
        app-service: customer-db
    spec:
      containers:
      - name: customer-mssql-deployment-container
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-db-secret
              key: SA_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: mssqlcustomerdb
      volumes:
        - name: mssqlcustomerdb
          persistentVolumeClaim:
            claimName: customer-db-pvc