apiVersion: v1
kind: Service
metadata:
  name: product-ms-sql-load-balancer-service
spec:
  type: LoadBalancer
  ports:
  - name: lb-port
    protocol: TCP
    port: 1433
    targetPort: 1433
  selector: # this connects the service to the pods
    app-service: product-db

