version: '3.8'
services:
  app:
    container_name: orderapi
    image: thegeekspad/microshop-order-microservice
    restart: always
    ports:
      - 8081:8080
    environment:
      - MYSQL_HOST=orderdb
      - MYSQL_PORT=3306
      - MYSQL_DB=order_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - order-network
  db:
    container_name: orderdb
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=order_db
    networks:
      - order-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  order-network: