apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_HOST: rabbit-mq-cluster-ip-service
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"

---

apiVersion : v1
kind : ConfigMap
metadata:
  name : customer-api-config
data:
  host : customer-db-cluster-ip-service
  dbName: CustomerDBProd