apiVersion: v1
kind: Secret
data:
  SA_PASSWORD: RnJpZW5kc0ZvcmV2ZXIx
metadata:
  name: product-db-sa-password

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-ms-sql-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-ms-sql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: product-db
  template:
    metadata:
      labels:
        app-service: product-db
    spec:
      containers:
      - name: product-ms-sql-deployment-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-db-sa-password
              key: SA_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: product-db-volume
      volumes:
        - name: product-db-volume
          persistentVolumeClaim:
            claimName: product-ms-sql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: product-ms-sql-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: db-port
    protocol: TCP
    port: 1433
    targetPort: 1433
  selector: # this connects the service to the pods
    app-service: product-db

---

apiVersion: v1
kind: Service
metadata:
  name: product-ms-sql-load-balancer-service
spec:
  type: LoadBalancer
  ports:
  - name: lb-port
    protocol: TCP
    port: 1433
    targetPort: 1433
  selector: # this connects the service to the pods
    app-service: product-db

