apiVersion : v1
kind : ConfigMap
metadata:
  name : order-db-config
data:
  host : order-db-cluster-ip-service
  dbName: order_db_prod

---

apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # root
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: order-db
  template:
    metadata:
      labels:
        app-service: order-db
    spec:
      containers:
      - name: order-db-deployment-container
        image: mysql
        ports:
            - containerPort: 3306
              name: order-db-port
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef :
                  name: order-db-config
                  key: dbName

        volumeMounts:
        - mountPath: /var/lib/mysql
          name: order-db-persistent-storage
      volumes:
        - name: order-db-persistent-storage
          persistentVolumeClaim:
            claimName: order-db-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: order-db-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: db-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector: # this connects the service to the pods
    app-service: order-db


---
# Note: Load balancer service is created to test MYSQL connectivity from MYSQL Workbench. It is NOT being used for internal pod communication hence order-db-cluster-ip-service is used as hostname in API configuration

apiVersion: v1
kind: Service
metadata:
  name: order-db-load-balancer-service
spec:
  type: LoadBalancer
  ports:
  - name: lb-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector: 
    app-service: order-db

