apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TSFjckBzaEBwSzhT 
  MYSQL_DATABASE: b3JkZXJfZGI=

  # M!cr@sh@pK8S
# order_db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: order-db
  template:
    metadata:
      labels:
        app-service: order-db
    spec:
      containers:
      - name: order-db-deployment-container
        image: mysql
        ports:
            - containerPort: 3306
              name: db-port
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: MYSQL_DATABASE
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: order-db-persistent-storage
      volumes:
        - name: order-db-persistent-storage
          persistentVolumeClaim:
            claimName: order-db-pvc
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: order-db-cluster-ip-service
# spec:
#   type: ClusterIP
#   ports:
#   - name: db-port
#     protocol: TCP
#     port: 3306
#     targetPort: 3306
#   selector: # this connects the service to the pods
#     app-service: order-db

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: order-db-load-balancer-service
# spec:
#   type: LoadBalancer
#   ports:
#   - name: lb-port
#     protocol: TCP
#     port: 3306
#     targetPort: 3306
#   selector: # this connects the service to the pods
#     app-service: order-db

---

apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  clusterIP: None
  ports:
  - name: db-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector: 
    app-service: order-db

