apiVersion: v1
kind: Service
metadata:
  name: order-db-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: db-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector: # this connects the service to the pods
    app-service: order-db

