apiVersion: v1
kind: Service
metadata:
  name: order-db-load-balancer-service
spec:
  type: LoadBalancer
  ports:
  - name: lb-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector: # this connects the service to the pods
    app-service: order-db

