apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app-service: product
spec:
  selector:
    matchLabels:
      app-service: product
  replicas: 1
  template:
    metadata:
      labels:
        app-service: product
    spec:
      containers:
        - name: product-deployment-container
          image: thegeekspad/microshop-product-microservice
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: product-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector: # this connects the service to the pods
    app-service: product
---
apiVersion: v1
kind: Service
metadata:
  name: product-node-port-service
spec:
  type: NodePort
  ports:
    - port: 80 # this is the port on the service object and mapped to the node port
      targetPort: 80 # this is the port on the pod
      nodePort: 30003 # this is the port exposed on the node. Valid range is 30000-32767.
  selector: # this connects the service to the pods
    app-service: product

