apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app-service: customer
spec:
  selector:
    matchLabels:
      app-service: customer
  replicas: 1
  template:
    metadata:
      labels:
        app-service: customer
    spec:
      containers:
        - name: customer-deployment-container
          image: thegeekspad/microshop-customer-microservice
          ports:
          - containerPort: 80
