apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app-service: order-api
spec:
  selector:
    matchLabels:
      app-service: order-api
  replicas: 1
  template:
    metadata:
      labels:
        app-service: order-api
    spec:
      containers:
        - name: order-api-deployment-container
          image: thegeekspad/microshop-order-microservice
          ports:
              - name: http-port
                containerPort: 8080
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: order-api-config
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: order-api-config
                key: dbName
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: order-api-secret
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-api-secret
                key: DB_PASSWORD
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-config
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-config
                key: RABBITMQ_PORT