apiVersion: v1
kind: Secret
metadata:
  name: order-api-secret
type: Opaque
data:
  MYSQL_HOST: b3JkZXItZGItbG9hZC1iYWxhbmNlci1zZXJ2aWNl # order-db-load-balancer-service
  MYSQL_PORT: MzMwNg== # 3306
  MYSQL_DB: b3JkZXJfZGI= # order_db
  MYSQL_USER: cm9vdA== # root
  MYSQL_PASSWORD: TSFjckBzaEBwSzhT  # M!cr@sh@pK8S
