apiVersion: v1
kind: Service
metadata:
  name: customer-mssql-cluster-ip-service
spec:
  type: ClusterIP
  ports:
  - name: db-port
    protocol: TCP
    port: 1433
    targetPort: 1433
  selector: # this connects the service to the pods
    app-service: customer-db

