apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-cluster-ip-service # this value must match the rabbit mq config in the connection string of the service project
spec:
  type: ClusterIP
  ports:
  - name: management-port
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: messaging-port
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app-service: rabbit-mq-message-broker

