version: '3.4'

services:
    customer-microservice:
        container_name: customer-ms
        image: thegeekspad/microshop-customer-microservice
        depends_on:
            - seq
            - sql
        env_file:
            - .env
        ports:
            - 5000:80
        networks:
            - microshop-network
    seq:
        container_name: seq
        image: datalust/seq
        ports: 
            - 5341:80
        env_file:
            - .env
        networks:
            - microshop-network
    sql:
        container_name: customer-db
        build:
            context: .
            dockerfile: sql/prod/sql.Dockerfile
        restart: always
        ports:
            - 1440:1433   
        env_file:
            - .env
        networks:
            - microshop-network
networks:
  microshop-network:



