name: Customer MicroService Build and Deploy to Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - src/**
      - src/Services/Customer/**
      - .github/workflows/customer-microservice.yml
      
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**
      - src/Services/Customer/**
      - .github/workflows/customer-microservice.yml

env:
  SERVICE: customer-microservice
  IMAGE_NAME: thegeekspad/customer-microservice
  DOTNET_VERSION: 7.0.x
  PROJECT_PATH: src/services/customer/Customer.MicroService
  UNIT_TEST_PROJECT_PATH: src/services/customer/Customer.MicroService.UnitTests
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore Dependencies
      run: dotnet restore ${{env.PROJECT_PATH}}/*.csproj
    - name: Build Project
      run: dotnet build --no-restore --verbosity normal ${{env.PROJECT_PATH}}/*.csproj
    - name: Restore Dependencies Unit Test Project
      run: dotnet restore ${{env.UNIT_TEST_PROJECT_PATH}}/*.csproj
    - name: Build Unit Test Project
      run: dotnet build --no-restore --verbosity normal ${{env.UNIT_TEST_PROJECT_PATH}}/*.csproj
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal ${{env.UNIT_TEST_PROJECT_PATH}}/*.csproj
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .
    - name: Log in to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push Docker image to Docker Hub
      run: docker push $IMAGE_NAME
    

