name: Customer MicroService Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVICE: customer-microservice
  IMAGE: thegeekspad/customer-microservice
  DOTNET_VERSION: 7.0.x
  PROJECT_PATH: ./src/services/customer/Customer.MicroService
  UNIT_TEST_PROJECT_PATH: ./src/services/customer/Customer.MicroService.UnitTests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_PATH}}/*.csproj
    - name: Build
      run: dotnet build --no-restore --verbosity normal ${{env.PROJECT_PATH}}/*.csproj
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal ${{env.UNIT_TEST_PROJECT_PATH}}/*.csproj
#     - name: Build the Docker image
#       run: docker build . --file ${{env.PROJECT_PATH}}/Dockerfile --tag ${{env.IMAGE}}:latest 
