name: Build Product Service Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Working Directory
      working-directory: ../../src/services/product/Product.MicroService
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build the Docker image
      run: docker build --file src/services/product/Product.MicroService/Dockerfile --tag thegeekspad/microshop-product-microservice:$(date +%s) .
